version: '3.8'

services:
  web:
    build: ./nginx
    depends_on:
      - backend
    ports:
      - ${USER_INTERFACE_PORT}:${WEB_SERVER_PORT}
    env_file:
      - ./.env
    environment:
      - SERVER_IP_ADDRESS=${SERVER_IP_ADDRESS}
    networks:
      - webapp

  backend:
    build: ./backend
    env_file:
      - ./.env
    environment:
      - SERVER_IP_ADDRESS=${SERVER_IP_ADDRESS}
    networks:
      - webapp

networks:
  webapp:


