version: '3.8'

services:
  web:
    build: ./nginx
    depends_on:
      - backend
    ports:
      - ${USER_INTERFACE_PORT}:${WEB_SERVER_PORT}
    env_file:
      - ./.env
    environment:
      - SERVER_IP_ADDRESS=${SERVER_IP_ADDRESS}
      - SERVER_IP_PORT=${WEB_SERVER_PORT}
    volumes:
      - web_log:/var/log/nginx
    networks:
      - webapp

  backend:
    build: ./backend
    env_file:
      - ./.env
    environment:
      - SERVER_IP_ADDRESS=${SERVER_IP_ADDRESS}
      - LOG_FOLDER=${BACKEND_SERVER_LOG_PATH}
    networks:
      - webapp
    volumes:
      - backend_log:${BACKEND_SERVER_LOG_PATH}

networks:
  webapp:

volumes:
  web_log:
  backend_log:

